/**
 * This class is generated by jOOQ
 */
package yvkm.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import yvkm.jooq.tables.BookToBookStore;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookToBookStoreRecord extends UpdatableRecordImpl<BookToBookStoreRecord> implements Record3<String, Long, Integer> {

	private static final long serialVersionUID = -1667644396;

	/**
	 * Setter for <code>jooq.book_to_book_store.name</code>.
	 */
	public void setName(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>jooq.book_to_book_store.name</code>.
	 */
	public String getName() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>jooq.book_to_book_store.book_id</code>.
	 */
	public void setBookId(Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>jooq.book_to_book_store.book_id</code>.
	 */
	public Long getBookId() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>jooq.book_to_book_store.stock</code>.
	 */
	public void setStock(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>jooq.book_to_book_store.stock</code>.
	 */
	public Integer getStock() {
		return (Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<String, Long> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, Long, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, Long, Integer> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return BookToBookStore.BOOK_TO_BOOK_STORE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return BookToBookStore.BOOK_TO_BOOK_STORE.BOOK_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return BookToBookStore.BOOK_TO_BOOK_STORE.STOCK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getBookId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getStock();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookToBookStoreRecord value1(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookToBookStoreRecord value2(Long value) {
		setBookId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookToBookStoreRecord value3(Integer value) {
		setStock(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookToBookStoreRecord values(String value1, Long value2, Integer value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BookToBookStoreRecord
	 */
	public BookToBookStoreRecord() {
		super(BookToBookStore.BOOK_TO_BOOK_STORE);
	}

	/**
	 * Create a detached, initialised BookToBookStoreRecord
	 */
	public BookToBookStoreRecord(String name, Long bookId, Integer stock) {
		super(BookToBookStore.BOOK_TO_BOOK_STORE);

		setValue(0, name);
		setValue(1, bookId);
		setValue(2, stock);
	}
}
