/**
 * This class is generated by jOOQ
 */
package yvkm.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import yvkm.jooq.tables.Author;
import yvkm.jooq.tables.Book;
import yvkm.jooq.tables.BookStore;
import yvkm.jooq.tables.BookToBookStore;
import yvkm.jooq.tables.Language;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jooq extends SchemaImpl {

	private static final long serialVersionUID = 1360001708;

	/**
	 * The reference instance of <code>jooq</code>
	 */
	public static final Jooq JOOQ = new Jooq();

	/**
	 * No further instances allowed
	 */
	private Jooq() {
		super("jooq");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Author.AUTHOR,
			Book.BOOK,
			BookStore.BOOK_STORE,
			BookToBookStore.BOOK_TO_BOOK_STORE,
			Language.LANGUAGE);
	}
}
