/**
 * This class is generated by jOOQ
 */
package yvkm.jooq;


import javax.annotation.Generated;

import yvkm.jooq.tables.Author;
import yvkm.jooq.tables.Book;
import yvkm.jooq.tables.BookStore;
import yvkm.jooq.tables.BookToBookStore;
import yvkm.jooq.tables.Language;


/**
 * Convenience access to all tables in jooq
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table jooq.author
	 */
	public static final Author AUTHOR = yvkm.jooq.tables.Author.AUTHOR;

	/**
	 * The table jooq.book
	 */
	public static final Book BOOK = yvkm.jooq.tables.Book.BOOK;

	/**
	 * The table jooq.book_store
	 */
	public static final BookStore BOOK_STORE = yvkm.jooq.tables.BookStore.BOOK_STORE;

	/**
	 * The table jooq.book_to_book_store
	 */
	public static final BookToBookStore BOOK_TO_BOOK_STORE = yvkm.jooq.tables.BookToBookStore.BOOK_TO_BOOK_STORE;

	/**
	 * The table jooq.language
	 */
	public static final Language LANGUAGE = yvkm.jooq.tables.Language.LANGUAGE;
}
